const bookData = [
  {
    adminId: "ed09c474-0e77-48a4-8d1e-1f7844bd5290",
    title: "Start With Why",
    author: "Simon Sinek",
    category: ["Business"],
    availableqty: 8,
    description:
      "Explains how leaders inspire action by starting with purpose.",
    imgurl: "https://images-na.ssl-images-amazon.com/images/I/71wR6Gq+X-L.jpg",
  },
  {
    adminId: "420a704f-5d80-47c2-ba1e-7781f87f8b7d",
    title: "Algorithms to Live By",
    author: "Brian Christian",
    category: ["Technology"],
    availableqty: 6,
    description:
      "Shows how computer algorithms can improve everyday decisions.",
    imgurl: "https://images-na.ssl-images-amazon.com/images/I/71x7zZx3fEL.jpg",
  },
  {
    adminId: "a82a26d1-ae2a-465c-85c3-bec52269489e",
    title: "The Power of Habit",
    author: "Charles Duhigg",
    category: ["SelfHelp"],
    availableqty: 10,
    description: "Explains how habits work and how they can be changed.",
    imgurl: "https://images-na.ssl-images-amazon.com/images/I/81u0OQ2nNJL.jpg",
  },
  {
    adminId: "1f4a4601-c1f4-4366-aa1f-acafca4af871",
    title: "Astrophysics for People in a Hurry",
    author: "Neil deGrasse Tyson",
    category: ["Science"],
    availableqty: 5,
    description: "A concise introduction to modern astrophysics concepts.",
    imgurl: "https://images-na.ssl-images-amazon.com/images/I/71Zk1r7CwPL.jpg",
  },
  {
    adminId: "66a44cec-6202-4df9-b9a7-e5fd90ca516a",
    title: "The Art of War",
    author: "Sun Tzu",
    category: ["History"],
    availableqty: 14,
    description: "An ancient guide on strategy, leadership, and warfare.",
    imgurl: "https://images-na.ssl-images-amazon.com/images/I/81c0kL6FJCL.jpg",
  },
  {
    adminId: "eb6fec6e-2319-4e37-ba22-b45f8cac2605",
    title: "Flash Boys",
    author: "Michael Lewis",
    category: ["Finance"],
    availableqty: 7,
    description:
      "Investigates high-frequency trading in modern financial markets.",
    imgurl: "https://images-na.ssl-images-amazon.com/images/I/71RZpE8W8xL.jpg",
  },
  {
    adminId: "4ea6d48a-8164-4bcf-b2f5-a5176e0d1613",
    title: "The Design of Everyday Things",
    author: "Don Norman",
    category: ["Technology"],
    availableqty: 9,
    description: "Explains why good design makes products easier to use.",
    imgurl: "https://images-na.ssl-images-amazon.com/images/I/71v1JcP6uWL.jpg",
  },
  {
    adminId: "ed09c474-0e77-48a4-8d1e-1f7844bd5290",
    title: "Moneyball",
    author: "Michael Lewis",
    category: ["Business"],
    availableqty: 6,
    description: "How data analytics revolutionized professional baseball.",
    imgurl: "https://images-na.ssl-images-amazon.com/images/I/81E4EJq5C5L.jpg",
  },
  {
    adminId: "1f4a4601-c1f4-4366-aa1f-acafca4af871",
    title: "Drive",
    author: "Daniel H. Pink",
    category: ["SelfHelp", "Business"],
    availableqty: 8,
    description: "Explains what truly motivates people at work and in life.",
    imgurl:
      "https://images-na.ssl-images-amazon.com/images/I/71g2ednj0JL._AC_SL1500_.jpg",
  },
  {
    adminId: "420a704f-5d80-47c2-ba1e-7781f87f8b7d",
    title: "The Phoenix Project",
    author: "Gene Kim",
    category: ["Technology", "Business"],
    availableqty: 6,
    description: "A novel about IT, DevOps, and helping a business win.",
    imgurl: "https://images-na.ssl-images-amazon.com/images/I/81vvgZqCskL.jpg",
  },
  {
    adminId: "4ea6d48a-8164-4bcf-b2f5-a5176e0d1613",
    title: "The Silk Roads",
    author: "Peter Frankopan",
    category: ["History"],
    availableqty: 5,
    description: "A new global history centered on the East.",
    imgurl: "https://images-na.ssl-images-amazon.com/images/I/81YxH8w9nPL.jpg",
  },
  {
    adminId: "66a44cec-6202-4df9-b9a7-e5fd90ca516a",
    title: "Thinking in Bets",
    author: "Annie Duke",
    category: ["Business", "SelfHelp"],
    availableqty: 7,
    description: "How to make smarter decisions under uncertainty.",
    imgurl: "https://images-na.ssl-images-amazon.com/images/I/71fKZkT8u6L.jpg",
  },
  {
    adminId: "a82a26d1-ae2a-465c-85c3-bec52269489e",
    title: "The Big Short",
    author: "Michael Lewis",
    category: ["Finance"],
    availableqty: 6,
    description: "The story of the 2008 financial crisis.",
    imgurl: "https://images-na.ssl-images-amazon.com/images/I/81yZ9Q2Z2EL.jpg",
  },
  {
    adminId: "eb6fec6e-2319-4e37-ba22-b45f8cac2605",
    title: "Cosmos",
    author: "Carl Sagan",
    category: ["Science", "Physics"],
    availableqty: 9,
    description: "A journey through space, time, and human understanding.",
    imgurl: "https://images-na.ssl-images-amazon.com/images/I/91zbi9M+mKL.jpg",
  },
  {
    adminId: "ed09c474-0e77-48a4-8d1e-1f7844bd5290",
    title: "The Hard Thing About Hard Things",
    author: "Ben Horowitz",
    category: ["Business"],
    availableqty: 8,
    description: "Real advice on building and running startups.",
    imgurl: "https://images-na.ssl-images-amazon.com/images/I/81hd5Bv8YRL.jpg",
  },
  {
    adminId: "1f4a4601-c1f4-4366-aa1f-acafca4af871",
    title: "Brief Answers to the Big Questions",
    author: "Stephen Hawking",
    category: ["Science", "Physics"],
    availableqty: 4,
    description: "Hawking’s final thoughts on the universe and humanity.",
    imgurl: "https://images-na.ssl-images-amazon.com/images/I/91X6e7k8uHL.jpg",
  },
  {
    adminId: "420a704f-5d80-47c2-ba1e-7781f87f8b7d",
    title: "The E-Myth Revisited",
    author: "Michael E. Gerber",
    category: ["Business"],
    availableqty: 10,
    description: "Why most small businesses fail and how to fix them.",
    imgurl: "https://images-na.ssl-images-amazon.com/images/I/81YpYJ9DkUL.jpg",
  },
  {
    adminId: "4ea6d48a-8164-4bcf-b2f5-a5176e0d1613",
    title: "The Order of Time",
    author: "Carlo Rovelli",
    category: ["Physics", "Science"],
    availableqty: 5,
    description: "A poetic exploration of time and reality.",
    imgurl: "https://images-na.ssl-images-amazon.com/images/I/81ZK5Zz8JUL.jpg",
  },
  {
    adminId: "66a44cec-6202-4df9-b9a7-e5fd90ca516a",
    title: "Principles",
    author: "Ray Dalio",
    category: ["Business", "Finance"],
    availableqty: 12,
    description: "Life and work principles from a legendary investor.",
    imgurl: "https://images-na.ssl-images-amazon.com/images/I/91f8XHq8KFL.jpg",
  },
  {
    adminId: "a82a26d1-ae2a-465c-85c3-bec52269489e",
    title: "The Goal",
    author: "Eliyahu M. Goldratt",
    category: ["Business"],
    availableqty: 6,
    description: "A novel about improving manufacturing and operations.",
    imgurl: "https://images-na.ssl-images-amazon.com/images/I/81yR9X6zYQL.jpg",
  },
  {
    adminId: "eb6fec6e-2319-4e37-ba22-b45f8cac2605",
    title: "Why We Sleep",
    author: "Matthew Walker",
    category: ["Science"],
    availableqty: 7,
    description: "The science of sleep and its impact on health.",
    imgurl: "https://images-na.ssl-images-amazon.com/images/I/81Y8xH6n+VL.jpg",
  },
  {
    adminId: "ed09c474-0e77-48a4-8d1e-1f7844bd5290",
    title: "Thinking in Systems",
    author: "Donella H. Meadows",
    category: ["Science"],
    availableqty: 5,
    description: "An introduction to systems thinking and complexity.",
    imgurl: "https://images-na.ssl-images-amazon.com/images/I/81QmJQz4Y2L.jpg",
  },

  {
    adminId: "420a704f-5d80-47c2-ba1e-7781f87f8b7d",
    title: "Superforecasting",
    author: "Philip E. Tetlock",
    category: ["Science"],
    availableqty: 6,
    description: "The art and science of prediction.",
    imgurl: "https://images-na.ssl-images-amazon.com/images/I/71L6XJXJ2DL.jpg",
  },
  {
    adminId: "4ea6d48a-8164-4bcf-b2f5-a5176e0d1613",
    title: "Hackable",
    author: "Ted Harrington",
    category: ["Technology"],
    availableqty: 7,
    description: "How hackers think and how to protect systems.",
    imgurl: "https://images-na.ssl-images-amazon.com/images/I/81p2N7cU1QL.jpg",
  },
  {
    adminId: "66a44cec-6202-4df9-b9a7-e5fd90ca516a",
    title: "The Black Swan",
    author: "Nassim Nicholas Taleb",
    category: ["Finance"],
    availableqty: 9,
    description: "The impact of rare and unpredictable events.",
    imgurl: "https://images-na.ssl-images-amazon.com/images/I/81tQpZ+QJBL.jpg",
  },
  {
    adminId: "a82a26d1-ae2a-465c-85c3-bec52269489e",
    title: "The Information",
    author: "James Gleick",
    category: ["Technology", "History"],
    availableqty: 5,
    description: "A history of information from language to the digital age.",
    imgurl: "https://images-na.ssl-images-amazon.com/images/I/81xM9JY5nQL.jpg",
  },
  {
    adminId: "eb6fec6e-2319-4e37-ba22-b45f8cac2605",
    title: "Factfulness",
    author: "Hans Rosling",
    category: ["Science"],
    availableqty: 11,
    description: "Why the world is better than we think, backed by data.",
    imgurl: "https://images-na.ssl-images-amazon.com/images/I/81QzW7J9RJL.jpg",
  },
];

module.exports = { bookData };
